[package]
name = "nalgebra-numpy"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"
license = "BSD-2-Clause"

[dependencies]
nalgebra = "0.19.0"
numpy = "0.7.0"
pyo3 = "0.8.2"

[dev-dependencies]
inline-python = "0.3.1"
