[package]
name = "nalgebra-numpy"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
generic-array = "0.13.2"
nalgebra = "0.19.0"
ndarray = "0.13.0"
numpy = "0.7.0"
pyo3 = "0.8.2"

[dev-dependencies]
inline-python = "0.3.1"
